### ISSUE TITLE
What version of Python should I run this on?

### ISSUE THREAD

**Issue by kalepail** [Shaptic/sep-39#1]
I don't know jack about python but when I run this I'm getting syntax errors. I'm guessing it's my setup. I don't want to get bogged down in a language I'm not proficient in but I do want to ensure your reference implementation looks like mine in JS to ensure we're on the same page before finalizing the sep.

```bash
% python -m unittest discover
E
======================================================================
ERROR: test_sep39 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_sep39
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/tylervanderhoeven/Desktop/Web/Stellar/sep-39/test_sep39.py", line 109
    print(f"  {growth:.2f}% growth")
                                  ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

```bash
% python sep39.py sep39.py
  File "sep39.py", line 11
    return f"{media_type}{';' if params else ''}" + \
                                                ^
SyntaxError: invalid syntax
```

**Comment by kalepail** [comment]
Python v3

✅
